### Ex 1
 Please write a function to calculate the Euclidean distance between two vectors.
 The Euclidean distance between two vectors x and y is defined as the square root of
 the sum of the squares of the differences between corresponding elements of the
 vectors. Your function should produce the same result as np.linalg.norm(x-y).
 Test inputs: x = [1, 2, 3] and y = [4, 5, 6]. Show both results from your Euclidean
 distance function and from “np.linalg.norm(x- y)”

In [4]:
import numpy as np

x = [1, 2, 3]
y = [4, 5, 6]

In [6]:
def euclideanDistance(x, y):
    # Ensure the vectors have the same length
    if len(x) != len(y):
        raise ValueError("Vectors must have the same length")
    
    # Calculate the squared differences
    #sqrt( sum(x-y)^2)
    squared_diff = [(a - b) ** 2 for a, b in zip(x, y)]
    
    # Sum of squared differences
    sum_squared_diff = sum(squared_diff)
    
    # Return the square root of the sum of squared differences
    return np.sqrt(sum_squared_diff)

In [8]:
euclideanDistance(x, y)

5.196152422706632

### Ex 2. 
 Please implement a function in Python to calculate the cosine similarity between
 text1 = "Machine learning is fun" and text2 = "Fun is machine learning".

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
def calculate_cosine_similarity(text1, text2):
    # Initialize CountVectorizer
    vectorizer = CountVectorizer()

    # Create the vector representation of the texts
    vectorized_text = vectorizer.fit_transform([text1, text2])

    # Calculate cosine similarity
    similarity_matrix = cosine_similarity(vectorized_text)

    # Extract cosine similarity score from the matrix
    cosine_sim = similarity_matrix

    return cosine_sim

In [21]:
# Test texts
text1 = "Machine learning is fun"
text2 = "Fun is machine learning"

# Calculate cosine similarity
cosine_sim = calculate_cosine_similarity(text1, text2)
print(cosine_sim)

[[1. 1.]
 [1. 1.]]


### Ex 3. 
 Please fill out the ____?____ in the following levenshtein distance function.

In [27]:
def levenshtein_distance(str1, str2):
    m = len(str1)
    n = len(str2)
    dp = [[0] * (n + 1) for _ in range(m + 1)] # Array for Dynamic Programming states

    for i in range(m + 1):
        dp[i][0] = i
    for j in range(n + 1):
        dp[0][j] = j

    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if str1[i - 1] == str2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]
            else:
                dp[i][j] = min(dp[i - 1][j] ,        # deletion
                               dp[i][j - 1] ,        # insertion
                               dp[i - 1][j - 1]) + 1 # substitution

    return dp[m][n]




In [28]:
str1 = "kitten"
str2 = "sitting"
print("Levenshtein Distance:", levenshtein_distance(str1, str2))

Levenshtein Distance: 3


### manhattan, euclidean, chebyshev, cosine with sklearn

In [26]:
from sklearn.metrics.pairwise import pairwise_distances
X_serirs = [[0, 1], [1, 1],[1, 0],[1, -1],[0, -1],[-1, -1],[-1, 0],[-1, 1]]
for m in  ['manhattan','euclidean','chebyshev','cosine']:
    print(8*"-"+f"{m}"+8*"-")
    print(pairwise_distances(X_serirs, [[0, 0]], metric=m))

--------manhattan--------
[[1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]]
--------euclidean--------
[[1.        ]
 [1.41421356]
 [1.        ]
 [1.41421356]
 [1.        ]
 [1.41421356]
 [1.        ]
 [1.41421356]]
--------chebyshev--------
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
--------cosine--------
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
